version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  loan-calculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-calculator-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongo-data:
